name: Dependabot Alert to Slack

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Dependabot Alerts
        run: |
          curl -s -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
               -H "Accept: application/vnd.github+json" \
               https://api.github.com/repos/${{ github.repository }}/dependabot/alerts \
               > alerts.json

          echo "ALERT_COUNT=$(jq length alerts.json)" >> $GITHUB_ENV
          echo "PACKAGE=$(jq -r '.[0].dependency.package.name' alerts.json)" >> $GITHUB_ENV
          echo "SEVERITY=$(jq -r '.[0].security_advisory.severity' alerts.json)" >> $GITHUB_ENV
          echo "SUMMARY=$(jq -r '.[0].security_advisory.summary' alerts.json)" >> $GITHUB_ENV
          echo "URL=$(jq -r '.[0].html_url' alerts.json)" >> $GITHUB_ENV

      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": "🚨 New Dependabot Alert for ${{ env.PACKAGE }}",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "🚨 Dependabot Alert: ${{ env.SEVERITY }}"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Package:*\n${{ env.PACKAGE }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Severity:*\n${{ env.SEVERITY }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Summary:*\n${{ env.SUMMARY }}"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Alert"
                      },
                      "url": "${{ env.URL }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
